num = int(input('Number:'))
gen_ = (i for i in range(num) if i % 2 == 0)
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
print(next(gen_))
