# Generated by Django 3.2.9 on 2021-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=256, verbose_name="The film's title")),
                ('film_rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Old')])),
            ],
        ),
    ]
